### ISSUE TITLE
[Bug] EyesUtils.getCurrentFrameContentEntireSize(..) gets incorrect content size

### ISSUE THREAD

**Issue by By-ivan** [applitools/eyes.sdk.java3#31]
EyesUtils.getCurrentFrameContentEntireSize(..) gets incorrect content size and as result cannot capture either not full page not region.
Root cause: <html> element has css property height=100%;
In this case getCurrentFrameContentEntireSize(..) will calculate entire size incorrect.
Expected: correct screenshot
Actual: incorrect cut screenshot
[eyes-log.txt](https://github.com/applitools/eyes.sdk.java3/files/1314601/eyes-log.txt)
![fisrt](https://user-images.githubusercontent.com/17816729/30597666-5d0ab33a-9d60-11e7-92b0-985ac84ab271.png)
![second](https://user-images.githubusercontent.com/17816729/30597665-5d0a62c2-9d60-11e7-942a-4ae5d6ec8791.png)

 screenshot

**Comment by By-ivan** [comment]
CC: @valfirst

**Comment by By-ivan** [comment]
CC: @uarlouski

**Comment by danielputerman** [comment]
Hi @By-ivan, sorry for the late reply. Thanks for the detailed report! We'll investigate. The issue here is not that Applitools is getting the wrong content size, it's the fact that Chrome reports wrong content size :/ . I'll reproduce this issue and see how can we get the de-facto size from Chrome.

**Comment by danielputerman** [comment]
Fixed in [version 3.37](https://github.com/applitools/eyes.sdk.java3/releases/tag/v3.37). See PR #47
